<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-08-20T16:44:21 IST" name="Default suite" finished-at="2021-08-20T16:44:37 IST" duration-ms="16149">
    <groups>
    </groups>
    <test started-at="2021-08-20T16:44:21 IST" name="Default test" finished-at="2021-08-20T16:44:37 IST" duration-ms="16149">
      <class name="com.Project_TestingCRM.test.smoketests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.Project_TestingCRM.test.smoketests@683dbc2c]" started-at="2021-08-20T16:44:21 IST" name="setUp" finished-at="2021-08-20T16:44:21 IST" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="ApplicationOpen()[pri:0, instance:com.Project_TestingCRM.test.smoketests@683dbc2c]" started-at="2021-08-20T16:44:21 IST" name="ApplicationOpen" finished-at="2021-08-20T16:44:32 IST" duration-ms="11538" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ApplicationOpen -->
        <test-method signature="checkLogin()[pri:0, instance:com.Project_TestingCRM.test.smoketests@683dbc2c]" started-at="2021-08-20T16:44:32 IST" name="checkLogin" finished-at="2021-08-20T16:44:34 IST" duration-ms="1691" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at com.Project_TestingCRM.test.smoketests.checkLogin(smoketests.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkLogin -->
        <test-method is-config="true" signature="checkResult(org.testng.ITestResult)[pri:0, instance:com.Project_TestingCRM.test.smoketests@683dbc2c]" started-at="2021-08-20T16:44:34 IST" name="checkResult" finished-at="2021-08-20T16:44:35 IST" duration-ms="812" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=checkLogin status=FAILURE method=smoketests.checkLogin()[pri:0, instance:com.Project_TestingCRM.test.smoketests@683dbc2c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResult -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.Project_TestingCRM.test.smoketests@683dbc2c]" started-at="2021-08-20T16:44:35 IST" name="tearDown" finished-at="2021-08-20T16:44:37 IST" duration-ms="2050" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.Project_TestingCRM.test.smoketests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
